name: SimpleCosmetics
version: '2.4'
main: me.refrac.cosmetics.Cosmetics
api-version: '1.18'
authors: [GreenArrowlol, Refrac]

libraries:
  - dev.dejvokep:boosted-yaml:1.3.5

commands:
  cosmetics:
  cosmeticsreload:

permissions:
  simplecosmetics.use:
    description: Open the trails cosmetics menu.
    default: true