name: SimpleCosmetics
version: '2.2'
main: me.refrac.cosmetics.Cosmetics
api-version: '1.18'
authors: [GreenArrowlol, Refrac]

commands:
  cosmetics:
    aliases: [trails, playertrails]
  cosmeticsreload: